name: CI for Site VentePhone

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Verify files
      run: |
        ls -R
        if [ ! -f index.html ]; then
          echo "Error: index.html not found!"
          exit 1
        fi
    - name: Upload website
      uses: actions/upload-artifact@v4
      with:
        name: website-artifact
        path: .
